services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  app:
    
    image: ${DOCKER_IMAGE}
    container_name: facturas-app
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  rabbitmq_data:
